packages:
  - example
  - website

nodeLinker: hoisted
linkWorkspacePackages: true
minimumReleaseAge: 1440
allowBuilds:
  core-js: false
  esbuild: false
  unrs-resolver: false
  react-native-reserved-regions@https://codeload.github.com/appandflow/react-native-reserved-regions/tar.gz/1f0d1232ae75dfecfa605c55d51818438185a279: true
